### PR TITLE
Updated the feel of readme

### PR DESCRIPTION
**Pull request by ayushtiwari110**
## Description

I have updated the readme, and have tried to modernise it a bit and give it Rick and Morty feel <br />

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by PGautam27** [comment]
this is great but could you try to adjust the video? and ya also add a How to contribute section.

**Comment by PGautam27** [comment]
And not to forget. Mention about hacktoberfest and the contribution guideline

**Comment by ayushtiwari110** [comment]
Ya sure, I will update that now.

**Comment by PGautam27** [comment]
And take out the first video

**Comment by ayushtiwari110** [comment]
so i shall remove first video?

**Comment by PGautam27** [comment]
Yes

**Comment by ayushtiwari110** [comment]
sure

**Comment by PGautam27** [comment]
And don't forget to put a star on this repo

**Comment by ayushtiwari110** [comment]
you mean 'star'?

**Comment by ayushtiwari110** [comment]
hello i have updated those things , kindly check, and if u feel everything good, mark as hacktoberfest accepted

**Comment by PGautam27** [comment]
ok

**Comment by PGautam27** [comment]
nice

**Comment by ayushtiwari110** [comment]
Thanks! Had great time working on it.

**Comment by PGautam27** [comment]
> 

😁👍

**Pull request merged**
